[type/__timezone] Add zoneinfo_file explorer to check if timezone exists

diff --git a/type/__timezone/manifest b/type/__timezone/manifest
--- a/type/__timezone/manifest
+++ b/type/__timezone/manifest
@@ -26,6 +26,15 @@
 TZ=$(cat "${__object:?}/parameter/tz")
 os=$(cat "${__global:?}/explorer/os")
 localtime_file=/etc/localtime
+zoneinfo_file=$(cat "${__object:?}/explorer/zoneinfo_file")
+
+invalid_timezone() {
+	# NOTE: When the tzdata package was just installed, this might produce an
+	# invalid timezone error because the explorer has been run before the
+	# installation.
+	printf 'Invalid timezone: %s\n' "${TZ}" >&2
+	exit 1
+}
 
 # Some OSes require a timezone package to be installed first:
 case ${os}
@@ -44,9 +53,13 @@ esac
 case ${os}
 in
 	(alpine|coreos|debian|devuan|ubuntu)
+		test -n "${zoneinfo_file}" || invalid_timezone
+
 		echo "${TZ}" | __file /etc/timezone --source -
 		;;
 	(centos|redhat|scientific)
+		test -n "${zoneinfo_file}" || invalid_timezone
+
 		__file /etc/sysconfig/clock \
 			--owner root --group root --mode 644 \
 			--state exists
@@ -64,5 +77,4 @@ in
 		;;
 esac
 
-zoneinfo_file="/usr/share/zoneinfo/${TZ}"
 __link "${localtime_file}" --type symbolic --source "${zoneinfo_file}"
