[__user] Add support for querying Mac OS X OpenDirectory

diff --git a/type/__user/explorer/group b/type/__user/explorer/group
--- a/type/__user/explorer/group
+++ b/type/__user/explorer/group
@@ -1,6 +1,7 @@
 #!/bin/sh
 #
 # 2011 Steven Armstrong (steven-cdist at armstrong.cc)
+# 2019 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
 #
 # This file is part of cdist.
 #
@@ -21,11 +22,38 @@
 # Get an existing groups group entry.
 #
 
-if [ -f "$__object/parameter/gid" ]; then
-   gid=$(cat "$__object/parameter/gid")
-   if command -v getent >/dev/null; then
-      getent group "$gid" || true
-   elif [ -f /etc/group ]; then
-      grep -E "^(${gid}|([^:]+:){2}${gid}):" /etc/group || true
-   fi
+not_supported() {
+	echo "Your operating system ($("$__explorer/os")) is currently not supported." >&2
+	echo "Cannot extract group information." >&2
+	echo "Please contribute an implementation for it if you can." >&2
+	exit 1
+}
+
+
+if [ -f "$__object/parameter/gid" ]
+then
+	gid=$(cat "$__object/parameter/gid")
+	if command -v getent >/dev/null
+	then
+		getent group "$gid" || true
+	elif command -v dscl >/dev/null
+	then
+		# Mac OS X uses Directory Service to manage users and groups
+		dscl_grep() {
+			awk -F':( +|$)' "\$1 == \"$1\" { if (\$2) print \$2; while (getline > 0) { if (substr(\$0, 0, 1) == \" \") print substr(\$0, 2); else break } }"
+		}
+
+		if gprops=$(dscl -q . -read "/Groups/${name}")
+		then
+			printf '%s:%s:%u:%s\n' \
+				"$name" \
+				"$(echo "$gprops" | dscl_grep Password)" \
+				"$(echo "$gprops" | dscl_grep PrimaryGroupID)" \
+				"$(echo "$gprops" | dscl_grep GroupMembership | tr ' ' ',')"
+		fi
+	elif [ -f /etc/group ]; then
+		grep -E "^(${gid}|([^:]+:){2}${gid}):" /etc/group || true
+	else
+		not_supported
+	fi
 fi
diff --git a/type/__user/explorer/passwd b/type/__user/explorer/passwd
--- a/type/__user/explorer/passwd
+++ b/type/__user/explorer/passwd
@@ -1,6 +1,7 @@
 #!/bin/sh
 #
 # 2011 Steven Armstrong (steven-cdist at armstrong.cc)
+# 2019 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
 #
 # This file is part of cdist.
 #
@@ -21,10 +22,41 @@
 # Get an existing users passwd entry.
 #
 
+not_supported() {
+	echo "Your operating system ($("$__explorer/os")) is currently not supported." >&2
+	echo "Cannot extract passwd information." >&2
+	echo "Please contribute an implementation for it if you can." >&2
+	exit 1
+}
+
 name=$__object_id
 
-if command -v getent >/dev/null; then
-  getent passwd "$name" || true
-elif [ -f /etc/passwd ]; then
-  grep "^${name}:" /etc/passwd || true
+
+if command -v getent >/dev/null
+then
+	getent passwd "$name" || true
+elif command -v dscl >/dev/null
+then
+	# Mac OS X uses Directory Service to manage users and groups
+	dscl_grep() {
+		awk -F':( +|$)' "\$1 == \"$1\" { if (\$2) print \$2; while (getline > 0) { if (substr(\$0, 0, 1) == \" \") print substr(\$0, 2); else break } }"
+	}
+
+	if uprops=$(dscl -q . -read "/Users/${name}" \
+		NFSHomeDirectory Password PrimaryGroupID RealName UniqueID UserShell)
+	then
+		printf '%s:%s:%u:%u:%s:%s:%s\n' \
+			"$name" \
+			"$(echo "$uprops" | dscl_grep Password | sed -e 's/^\*\**$/*/')" \
+			"$(echo "$uprops" | dscl_grep UniqueID)" \
+			"$(echo "$uprops" | dscl_grep PrimaryGroupID)" \
+			"$(echo "$uprops" | dscl_grep RealName)" \
+			"$(echo "$uprops" | dscl_grep NFSHomeDirectory)" \
+			"$(echo "$uprops" | dscl_grep UserShell)"
+	fi
+elif [ -f /etc/passwd ]
+then
+	grep "^${name}:" /etc/passwd || true
+else
+	not_supported
 fi
diff --git a/type/__user/explorer/shadow b/type/__user/explorer/shadow
--- a/type/__user/explorer/shadow
+++ b/type/__user/explorer/shadow
@@ -1,6 +1,7 @@
 #!/bin/sh -e
 #
 # 2011 Steven Armstrong (steven-cdist at armstrong.cc)
+# 2019 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
 #
 # This file is part of cdist.
 #
@@ -21,20 +22,31 @@
 # Get an existing users shadow entry.
 #
 
+not_supported() {
+	echo "Your operating system ($("$__explorer/os")) is currently not supported." >&2
+	echo "Cannot extract shadow information." >&2
+	echo "Please contribute an implementation for it if you can." >&2
+	exit 1
+}
+
 name=$__object_id
 
 case $("$__explorer/os") in
-  'freebsd'|'netbsd'|'openbsd')
-    database='passwd'
-    ;;
-  # Default to using shadow passwords
-  *)
-    database='shadow'
-    ;;
+	'freebsd'|'netbsd'|'openbsd')
+		database=passwd
+	;;
+	*)
+		# Default to using shadow passwords
+		database=shadow
+	;;
 esac
 
-if command -v getent >/dev/null; then
-  getent "$database" "$name" || true
-elif [ -f /etc/shadow ]; then
-  grep "^${name}:" /etc/shadow || true
+if command -v getent >/dev/null
+then
+	getent "$database" "$name" || true
+elif [ -f /etc/shadow ]
+then
+	grep "^${name}:" /etc/shadow || true
+else
+	not_supported
 fi
