[type/__user] Lint

diff --git a/type/__user/explorer/shadow b/type/__user/explorer/shadow
--- a/type/__user/explorer/shadow
+++ b/type/__user/explorer/shadow
@@ -17,31 +17,32 @@
 # You should have received a copy of the GNU General Public License
 # along with skonfig-base. If not, see <http://www.gnu.org/licenses/>.
 #
-#
-# Get an existing users shadow entry.
+# Get an existing user's shadow entry.
 #
 
-name=$__object_id
+name=${__object_id:?}
 
-case $("${__explorer}/os") in
-  freebsd|netbsd)
-    database='passwd'
-    ;;
-  openbsd)
-    database='master.passwd'
-    ;;
-  *)
-    # Default to using shadow passwords
-    database='shadow'
-    ;;
+os=$(cat "${__explorer:?}/os")
+case ${os}
+in
+	(freebsd|netbsd)
+		db='passwd'
+		;;
+	(openbsd)
+		db='master.passwd'
+		;;
+	(*)
+		# Default to using shadow.
+		db='shadow'
+		;;
 esac
 
 if command -v getent >/dev/null 2>&1
 then
-  # shellcheck disable=SC2015
-  getent "${database}" "${name}" 2>/dev/null && exit || true  # fallback to file
+	# shellcheck disable=SC2015
+	getent "${db}" "${name}" 2>/dev/null && exit || :  # fallback to file
 fi
-if test -n "${database}" -a -f "/etc/${database}"
+if test -n "${db}" -a -f "/etc/${db}"
 then
-  grep -e "^${name}:" "/etc/${database}" || true  # ignore failure
+	grep -e "^${name}:" "/etc/${db}" || :  # ignore failure
 fi
