[type/__user] Allow different database and file names

diff --git a/type/__user/explorer/shadow b/type/__user/explorer/shadow
--- a/type/__user/explorer/shadow
+++ b/type/__user/explorer/shadow
@@ -1,6 +1,7 @@
 #!/bin/sh -e
 #
 # 2011 Steven Armstrong (steven-cdist at armstrong.cc)
+# 2019-2020 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
 #
 # This file is part of cdist.
 #
@@ -23,25 +24,34 @@
 
 name=$__object_id
 
-case $("${__explorer}/os") in
-  freebsd|netbsd)
+case $("${__explorer}/os")
+in
+  freebsd)
     database='passwd'
+    db_file='/etc/master.passwd'
     ;;
-  openbsd)
-    database='master.passwd'
+  macosx)
+    # Mac OS X doesn’t use files to store user accounts anymore.
+    # Most system users can still be found there, though.
+    # XXX: It is unclear if these files are updated by the system utilities!
+    db_file='/etc/master.passwd'
+    ;;
+  netbsd|openbsd)
+    db_file='/etc/master.passwd'
     ;;
   *)
     # Default to using shadow passwords
     database='shadow'
     ;;
 esac
+test -n "${db_file}" || db_file="/etc/${database}"
 
-if command -v getent >/dev/null 2>&1
+if test -n "${database}" && command -v getent >/dev/null 2>&1
 then
   # shellcheck disable=SC2015
   getent "${database}" "${name}" 2>/dev/null && exit || true  # fallback to file
 fi
-if test -n "${database}" -a -f "/etc/${database}"
+if test -f "${db_file}"
 then
-  grep -e "^${name}:" "/etc/${database}" || true  # ignore failure
+  grep -e "^${name}:" "${db_file}" || true  # ignore failure
 fi
