[type/__uci] Allow omission of --value parameter is --state absent

diff --git a/type/__uci/manifest b/type/__uci/manifest
--- a/type/__uci/manifest
+++ b/type/__uci/manifest
@@ -38,11 +38,17 @@ in
 esac
 
 needs_changes=false
+
 case $state_should
 in
 	(present)
 		# NOTE: order is ignored so rearranged is also fine.
 		in_list "${state_is}" 'present' 'rearranged' || needs_changes=true
+
+		test -s "${__object}/parameter/value" || {
+			echo 'The parameter --value is required.' >&2
+			exit 1
+		}
 		;;
 	(absent)
 		in_list "${state_is}" 'absent' || needs_changes=true
